# Generated by Django 4.1.7 on 2024-05-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0004_pages_description_en_pages_description_uk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('adress', models.TextField(blank=True, null=True)),
                ('coords_x', models.TextField(blank=True, null=True)),
                ('coords_y', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
