version: '3.12'

services:
  postgres-db:
    restart: always
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: kinocms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bbylfg

  web:
    restart: always
    build:
      context: .
    container_name: cinema
    command: make migrations
    depends_on:
      - postgres-db
    env_file: .env
    volumes:
      - static_volume:/usr/src/kinoCMS/static/
      - media_volume:/usr/src/kinoCMS/media/

  nginx:
    restart: always
    build:
      context: ./docker/nginx/.
    container_name: nginx
    volumes:
      - static_volume:/usr/src/kinoCMS/static/
      - media_volume:/usr/src/kinoCMS/media/
    ports:
      - '80:80'

  redis:
    restart: always
    image: "redis:alpine"

  celery:
    restart: always
    build:
      context: .
    command: make worker
    depends_on:
      - web
      - redis
      - postgres-db
    volumes:
      - static_volume:/usr/src/kinoCMS/static/
      - media_volume:/usr/src/kinoCMS/media/ 
    env_file: .env


volumes:
  static_volume:
  media_volume:
