# Generated by Django 4.2.9 on 2024-03-26 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(null=True, upload_to='')),
                ('top_image', models.ImageField(null=True, upload_to='')),
                ('url_trailer', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('seo_url', models.TextField(blank=True, null=True)),
                ('seo_title', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
                ('description_seo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Кинотеатр',
                'verbose_name_plural': 'Кинотеатры',
                'db_table': 'cinema',
            },
        ),
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер зала')),
                ('description', models.TextField(default='', verbose_name='Описание зала')),
                ('scheme_image', models.ImageField(default='-', upload_to='')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Время создавания')),
                ('top_image', models.ImageField(default='-', upload_to='', verbose_name='Топ баннер')),
                ('seo_url', models.TextField(blank=True, null=True)),
                ('seo_title', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
                ('description_seo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'db_table': 'cinemahall',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=7000, verbose_name='Описание')),
                ('main_image', models.ImageField(upload_to='', verbose_name='Картинка на главной')),
                ('url_trailer', models.CharField(max_length=512, verbose_name='URL трейлер')),
                ('type', models.CharField(blank=True, choices=[('3D', '3D'), ('2D', '2D'), ('IMAX', 'АйМакс')], max_length=4, null=True, verbose_name='Тип')),
                ('seo_url', models.TextField(blank=True, null=True)),
                ('seo_title', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
                ('description_seo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='MovieSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Сессия фыильма',
                'verbose_name_plural': 'Сессия фильмов',
                'db_table': 'moviesession',
            },
        ),
        migrations.CreateModel(
            name='Ticked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.moviesession', verbose_name='Айди сессии фильма')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'db_table': 'ticket',
            },
        ),
    ]
