# Generated by Django 4.2.9 on 2024-03-26 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticked',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Айди пользователя'),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie', verbose_name='Фильм'),
        ),
        migrations.AddField(
            model_name='movie',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery', verbose_name='Галлерея айди'),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='gallery_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery', verbose_name=''),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='movie_session_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.moviesession'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery'),
        ),
    ]
