# Generated by Django 4.1.7 on 2024-04-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='title_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='description_en',
            field=models.TextField(default='', null=True, verbose_name='Описание зала'),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='description_uk',
            field=models.TextField(default='', null=True, verbose_name='Описание зала'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_en',
            field=models.TextField(max_length=7000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_uk',
            field=models.TextField(max_length=7000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
