# Generated by Django 4.1.7 on 2024-04-22 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_cinema_description_en_cinema_description_uk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='gallery_id',
            new_name='gallery',
        ),
        migrations.RenameField(
            model_name='cinemahall',
            old_name='movie_session_id',
            new_name='movie_session',
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='cinema',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema', verbose_name='Айди кинотеатра'),
        ),
    ]
