# Generated by Django 4.1.7 on 2024-04-23 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_cinemahall_movie_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='cinema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema', verbose_name='Айди кинотеатра'),
        ),
    ]
