# Generated by Django 4.1.7 on 2024-04-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_cinemahall_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус'),
        ),
    ]
