# Generated by Django 4.1.7 on 2024-05-07 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_remove_cinemahall_movie_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='cinemahall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.cinemahall'),
        ),
    ]
