# Generated by Django 4.1.7 on 2024-05-08 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0009_moviesession_cinemahall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticked',
            name='movie_session_id',
        ),
        migrations.RemoveField(
            model_name='ticked',
            name='user_id',
        ),
        migrations.AddField(
            model_name='ticked',
            name='movie_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.moviesession', verbose_name='Сессия фильма'),
        ),
        migrations.AddField(
            model_name='ticked',
            name='row',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ряд'),
        ),
        migrations.AddField(
            model_name='ticked',
            name='seat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='ticked',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
