# Generated by Django 4.2.9 on 2024-03-26 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереї',
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка галереї')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Картинка галереї',
                'verbose_name_plural': 'Картинки галереї',
                'db_table': 'gallery_image',
            },
        ),
    ]
