# Generated by Django 4.2.9 on 2024-03-26 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('choice', models.CharField(max_length=1, verbose_name='Вибір якийсь')),
            ],
            options={
                'db_table': 'BackBanners',
            },
        ),
        migrations.CreateModel(
            name='MainBannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(verbose_name='Скорость')),
                ('active', models.BooleanField(verbose_name='Активно')),
            ],
            options={
                'db_table': 'MainBannerSettings',
            },
        ),
        migrations.CreateModel(
            name='NewsBannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(verbose_name='Скорость')),
                ('active', models.BooleanField(verbose_name='Активно')),
            ],
        ),
        migrations.CreateModel(
            name='NewsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('url', models.CharField(max_length=512, verbose_name='Ссылка')),
                ('text', models.CharField(max_length=100, verbose_name='Название')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.newsbannersettings')),
            ],
            options={
                'db_table': 'NewsBanner',
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('url', models.CharField(max_length=512, verbose_name='Ссылка')),
                ('text', models.CharField(max_length=100, verbose_name='Название')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.mainbannersettings')),
            ],
            options={
                'db_table': 'MainBanner',
            },
        ),
    ]
